<TabsScreen>:
    name: 'tabsscreen'
    MDTabs:
        id: tabs
    MDBoxLayout:
        id: status_bar
        md_bg_color: app.theme_cls.primary_color
        orientation: 'horizontal'
        padding: 10, 0, 10, 0
        size_hint_y: None
        height: 30
        MDLabel:
            id: capture_name
        Widget:
        MDLabel:
            id: packet_count
            text: 'Total Packets: 0'
            halign: 'right'   


